version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/arbiter-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/arbiter-dashboard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/arbiter-api"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/arbiter-dashboard"
    schedule:
      interval: "monthly"
